# Generated by Django 3.2.6 on 2021-09-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='download',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя профиля'),
        ),
    ]
