# Generated by Django 3.2.6 on 2021-09-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_alter_profile_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='profile',
        ),
        migrations.AddField(
            model_name='followers',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='followers.profile'),
        ),
    ]
