# Generated by Django 3.2.7 on 2021-09-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0005_alter_profile_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
